Events redesign
StochSS/stochss pull request #1151
Opened 2021-06-21 18:09 UTC by BryanRumsey

2021-06-22 20:10 UTC, jtcooper10 requested changes

2021-06-22 20:10 UTC, jtcooper10 commented on client/views/edit-event-assignment.js
> +    var specs = species.map(function (specie) {
Consider removing the "Variable" or "Parameter" options groups when there are no available variables/parameters

2021-06-22 21:08 UTC, BryanRumsey commented on client/templates/includes/eventAssignmentsEditor.pug
> +    button.btn.btn-outline-collapse(data-toggle="collapse" data-target="#collapse-event-assignments" data-hook="collapse") -
fixed

2021-06-23 12:39 UTC, BryanRumsey commented on client/templates/includes/eventDetails.pug
>      div.col-md-8.inline(id="event-trigger-expression" data-hook="event-trigger-expression")
fixed and fixed

2021-06-23 13:26 UTC, jtcooper10 approved these changes
Looks good.

2021-06-23 13:26 UTC, merged