3+D Parameter Sweep Plots
StochSS/stochss pull request #1181
Opened 2021-07-23 13:32 UTC by BryanRumsey

2021-07-29 18:42 UTC, briandrawert commented
![Screenshot from 2021-07-29 11-39-30](https://user-images.githubusercontent.com/1413538/127548169-2d86188a-7ac6-46d3-ba9c-2af57eda1f0b.png)
Extra Quotes around "Review Model" on parameter sweep page.

2021-07-29 20:43 UTC, briandrawert approved these changes

2021-08-03 01:45 UTC, jtcooper10 requested changes
Everything works except for what I left comments about. Tested in Edge on Windows 11.

2021-08-03 01:45 UTC, jtcooper10 commented on stochss/handlers/util/parameter_sweep_2d.py
> +                                          xaxis=dict(title=f"<b>{params[0]['name']}</b>"),
This is a XSS vulnerability, and allows for arbitrary code execution on published models.

To replicate: set your species name to a JavaScript code segment, like `<script>window.alert("ping!")</script>` and run a parameter sweep simulation. It's validated on the front end, but not on the server.

![image](https://user-images.githubusercontent.com/42880781/127943507-deb63779-8162-4363-a793-d9a33c41aca7.png)

2021-08-03 01:45 UTC, jtcooper10 commented on stochss/handlers/util/parameter_sweep_1d.py
> +        title = f"<b>Parameter Sweep - Variable: {species}</b>"
Same thing here: inline species name getting returned to the client is a XSS vulnerability

2021-08-04 16:02 UTC, briandrawert commented
`overflow-x: scroll;`  on the parameter sliders creates scrollbars when there should be none

2021-08-04 16:06 UTC, briandrawert commented
When a checkbox is clicked on the sweep tab, 'disable' all other "fixed" sliders if their fixed checkbox is not selected.

2021-08-04 16:46 UTC, briandrawert commented on client/templates/includes/sweepParameterRange.pug
> +      div.horizontal-scroll(data-hook=this.model.elementID + "-current-value" style="overflow-x: none;")=this.model.range[0]
none => visible

2021-08-04 16:53 UTC, briandrawert approved these changes

2021-08-04 16:54 UTC, merged