Fix npm issues
StochSS/stochss pull request #1232
Opened 2021-08-06 18:59 UTC by briandrawert

2021-08-13 13:08 UTC, BryanRumsey requested changes
Tested on MacOS and the npm changes work with `make`, `make watch`, `make hub`, and `make run_hub_staging`.  The launch web browser script doesn't work.

2021-08-14 17:15 UTC, jtcooper10 requested changes
Does not work on Windows, but the fixes should be very simple (comments included). Getting the same `ModuleNotFound` error as Bryan, as well.

Other than that, everything works great. Tested on Windows 11.

2021-08-16 12:15 UTC, BryanRumsey commented on launch_webbrowser.py
> +import docker
installing docker.py fixed this issue

2021-08-16 12:16 UTC, BryanRumsey approved these changes

2021-08-16 17:26 UTC, seanebum approved these changes

2021-08-16 22:58 UTC, briandrawert commented on Makefile
> +	python3 launch_webbrowser.py &
Should be resolved, please re-check.

2021-08-16 23:56 UTC, jtcooper10 approved these changes

2021-08-17 12:41 UTC, BryanRumsey approved these changes

2021-08-17 15:19 UTC, seanebum commented on launch_webbrowser.py
> +        webbrowser.open_new(jupyter_url)
`webbrowser.open_new_tab(jupyter_url)` may be preferrable here

2021-08-17 15:27 UTC, seanebum approved these changes

2021-08-17 15:27 UTC, merged